### ISSUE TITLE
URL Query params seem trucated

### ISSUE THREAD

**Issue by serge-fabiano** [orubel/beapi-bench#9]
Shooting this URL:
https://xxx.com/client/api/Users?Issuer=true&Limit=100&SortFields=name&SortDirs=asc

Got in the server's log:
https://xxx.com/client/api/Users?Issuer

URL is truncated after the Issuer Query param.

**Comment by orubel** [comment]
Sorry about the late response. 

Did it parse on your side fine? It should NOT be reporting variables in the log; this is considered insecure. This literally depends on how your server is truncating that call. I don't handle this, this is your server.
